//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCard
    {
        public string BankName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CardNumber { get; set; }
        public string ValidDate { get; set; }
        public string Price { get; set; }
    }
}
